labels = {
    'plain': 'Write internal logs in plain text',
    'json': 'Write internal logs in JSON format',
    'address': "Address",
    'port': "Port",
    'protocol': "Protocol",
    'crypto_method': 'Method used to encrypt communications',
    'auto_restart':
    'Auto-restart the agent when receiving valid configuration from manager',
    'rootcheck': 'Rootcheck',
    'syscheck': 'Syscheck',
    'syscollector': 'Syscollector',
    'item': 'Item   ',
    'all': 'All ',
    'bin_path': 'Bin path',
    'type': 'Type ',
    'profile': 'Profile ',
    'path': 'Path ',
    'notify_time':
    'Time (in seconds) between agent checkings to the manager',
    'time-reconnect':
    'Time (in seconds) before attempting to reconnect',
    'server': 'List of managers to connect',
    'config-profile': 'Configuration profiles',
    'remote_conf': 'Remote configuration is enabled',
    'disabled': 'Enabled',
    'queue_size': 'Queue size',
    'events_per_second': 'Events per second',
    'system_audit': 'System audit',
    'base_directory': 'Base directory',
    'rootkit_files': 'Rootkit files database path',
    'rootkit_trojans': 'Rootkit trojans database path',
    'scanall': 'Scan the entire system',
    'skip_nfs': 'Skip scan on CIFS/NFS mounts',
    'frequency': 'Frequency (in seconds)',
    'check_dev': 'Check /dev path',
    'check_files': 'Check files',
    'check_if': 'Check network interfaces',
    'check_pids': 'Check processes IDs',
    'check_ports': 'Check network ports',
    'check_sys': 'Check anomalous system objects',
    'check_trojans': 'Check trojans',
    'check_unixaudit': 'Check UNIX audit',
    'enabled': 'Security configuration assessment enabled',
    'scan_on_start': 'Scan on start',
    'interval': 'Interval',
    'policies': 'Policies',
    'content': 'Evaluations',
    'scan-on-start': 'Scan on start',
    'timeout': 'Timeout (in seconds)',
    'scan-on-start': 'Scan on start',
    'java_path': 'Path to Java executable directory',
    'ciscat_path': 'Path to CIS-CAT executable directory',
    'wday': 'Day of the week to run scans',
    'time': 'Time of the day to run scans',
    'run_daemon': 'Auto-run the Osquery daemon',
    'add_labels': 'Use defined labels as decorators',
    'log_path': 'Path to the Osquery results log file',
    'config_path': 'Path to the Osquery configuration file',
    'scan-on-start': 'Scan on start',
    'network': 'Scan network interfaces',
    'os': 'Scan operating system info',
    'hardware': 'Scan hardware info',
    'packages': 'Scan installed packages',
    'ports': 'Scan listening network ports',
    'ports_all': 'Scan all network ports',
    'processes': 'Scan current processes',
    'ca_store': 'Use the following list of root CA certificates',
    'ca_verification': 'Validate WPKs using root CA certificate',
    'run_on_start': 'Run on start',
    'ignore_output': 'Ignore command output',
    'skip_verification': 'Ignore checksum verification',
    'tag': 'Command name',
    'command': 'Command',
    'verify_md5': 'Verify MD5 sum',
    'verify_sha1': 'Verify SHA1 sum',
    'verify_sha256': 'Verify SHA256 sum',
    'attempts': 'Number of attempts to execute the listener',
    'logformat': 'Log format',
    'syslog': 'Logs',
    'full_command': "Full command",
    'alias': 'Command alias',
    'ignore_binaries': 'Ignore binaries',
    'target': 'Targets',
    'file': 'Log location',
    'directories': 'Monitored directories',
    'nodiff': 'No diff directories',
    'ignore': 'Ignored files and directories',
    'restart_audit': 'Restart audit',
    'startup_healthcheck': 'Startup healthcheck',
    'whodata': 'Whodata',
    'email_to': "Email recipient",
    'email_alerts': "Email alerts",
    'localfile': 'Local Files',
    'sca': 'Configuration Assessment',
    'label': 'Labels',
    'os': 'OS',
    'name': 'Name ',
    'log_format': 'Log format',
    'audit': 'Audit',
    'repeated_offenders': 'List of timeouts (in minutes) for repeated offender',
    'check_winaudit': 'Check Windows audit',
    'windows_apps': 'Rootkit trojans database path',
    'check_winmalware': 'Check Windows apps',
    'check_winapps': 'Check Windows apps',
    'windows_malware': 'Rootkit trojans database path',
    'windows_audit_interval': "Interval to check directories' SACLs",
    'registry': 'Monitored',
    'registry_ignore': 'Ignored'
}
